#!/bin/bash
#-*- mode:sh -*-

################################################################
#### default options

################################################################
#### main

tc=$HOME/.fd-cache/translate/
pc=$HOME/.fd-cache/preprocess/
mkdir -pv $pc $tc

plan(){
    echo $(whoami)@$(hostname)
    OPTIONS=${OPTIONS:-"--search astar(lmcut())"}
    md5=$(cat domain.pddl problem.pddl | md5sum | cut -d' ' -f1)
    echo "md5 : $md5"
    (
        flock 9
        if [ -f $pc/$md5 ]
        then
            echo "reusing the preprocess output : $pc/$md5"
            cp $pc/$md5 output
        else
            if [ -f $tc/$md5 ]
            then
                echo "reusing the translation output : $tc/$md5"
                cp $tc/$md5 output.sas
            else
                echodo $fdscript --translate --log-level info domain.pddl problem.pddl \
                    && cp output.sas $tc/$md5
            fi
            
            echodo $fdscript --preprocess --log-level info output.sas \
                && cp output $pc/$md5
        fi
    ) 9>$pc/$md5.lock
    
    echodo $fdscript --search --validate --search-time-limit 180 \
        --plan-file $probdir/$probname.plan --log-level info output \
        $OPTIONS
}

finalize (){
    :
}

negatively-proven (){
    grep "Completely explored state space" $log &> /dev/null
}

report-results (){
    awk "/Plan cost:/{print $2}" $log | sort | head -n 1
}

plan-found (){
    ls $probdir/$probname.plan*
}

################################################################

. $SCRDIR/common.sh
