#!/bin/bash
#-*- mode:sh -*-

################################################################
#### default options

################################################################
#### main

find-fd-py (){
    find $1 -name "fast-downward.py"
}

find-fd-upward (){
    echo "finding FD installation from $1 ..."
    if [[ -d $1/downward ]]
    then
        fdscript=$(readlink -ef $(find-fd-py $1/downward))
    else
        if [[ $1 == / ]]
        then
            echo "failed to find Fast Downward installation (fast-downward.py) !"
            exit 1
        else
            find-fd-upward $(readlink -ef $1/..)
        fi
    fi
}

find-fd-upward $(dirname $(readlink -ef $0))

plan(){
    echo $(whoami)@$(hostname)
    OPTIONS=${OPTIONS:-"--alias seq-sat-lama-2011"}
    declare -a array=($OPTIONS)
    if [[ ${array[0]} == --alias ]]
    then
        echodo $fdscript \
            $OPTIONS \
            --run-all \
            --plan-file $probdir/$probname.plan \
            $(if $VERBOSE ; then echo "--log-level info" ; else echo "--log-level warning" ; fi) \
            domain.pddl problem.pddl
    else
        echodo $fdscript \
            --run-all \
            --search-memory-limit 2G \
            --plan-file $probdir/$probname.plan \
            $(if $VERBOSE ; then echo "--log-level info" ; else echo "--log-level warning" ; fi) \
            domain.pddl problem.pddl \
            $OPTIONS
    fi
}

finalize (){
    :
}

negatively-proven (){
    grep "Completely explored state space" log &> /dev/null
}

report-results (){
    awk "/Plan cost:/{print $2}" log | sort | head -n 1
}

plan-found (){
    ls $probdir/$probname.plan*
}

################################################################

. $SCRDIR/common.sh
