#!/bin/bash
#-*- mode:sh -*-

################################################################
#### default options

################################################################
#### main

plan(){
    echo $(whoami)@$(hostname)
    time echodo $fdscript --search --validate --alias lama-first \
        --plan-file $probdir/$probname.plan $log_options problem.pddl
}

finalize (){
    :
}

negatively-proven (){
    grep "Completely explored state space" $log &> /dev/null
}

report-results (){
    awk "/Plan cost:/{print $2}" $log | sort | head -n 1
}

plan-found (){
    ls $probdir/$probname.plan*
}

################################################################

. $SCRDIR/common.sh
