#!/bin/bash
#-*- mode:sh -*-

################################################################
#### default options

bin=$SCRDIR/macroff

################################################################
#### main

plan(){
    vecho $(whoami)@$(hostname)
    vechodo $bin $(if $VERBOSE ; then echo "-i 3" ; fi) $OPTIONS \
        -f problem.pddl -o domain.pddl
}

finalize (){
    if [[ -e problem.pddl.soln ]]
    then
        cat problem.pddl.soln | grep -v "^Time" > $probdir/$probname.plan
    else
        vecho "No plan found!"
    fi
}

negatively-proven (){
    grep "problem proven unsolvable" log
}

report-results (){
    local cost=$(cat plan | wc -l)
    [[ -e $plan && $cost -gt 0 ]] && echo "Plan cost: " $cost
    [[ -e $plan && $cost -gt 0 ]]
}

################################################################

. $SCRDIR/common.sh
