#!/bin/bash
#-*- mode:sh -*-

################################################################
#### default options

bin=$SCRDIR/macroff
options=""

################################################################
#### main

plan(){
    vecho $(whoami)@$(hostname)
    vechodo $bin $(if $VERBOSE ; then echo "-i 3" ; fi) $options \
        -f problem.pddl -o domain.pddl
}

finalize (){
    if [[ -e problem.pddl.soln ]]
    then
        cat problem.pddl.soln | grep -v "^Time" > $probdir/$probname.plan
    else
        vecho "No plan found!"
    fi
}

negatively-proven (){
    grep "problem proven unsolvable" log
}

report-results (){
    cat plan | wc -l
}

################################################################

. $SCRDIR/common.sh
