#!/bin/bash
#-*- mode:sh -*-

################################################################
#### default options

################################################################
#### main

find-fd-py (){
    find $1 -name "fast-downward.py"
}

find-fd-upward (){
    echo "finding FD installation from $1 ..."
    if [[ -d $1/downward ]]
    then
        fdscript=$(readlink -ef $(find-fd-py $1/downward))
    else
        if [[ $1 == / ]]
        then
            echo "failed to find Fast Downward installation (fast-downward.py) !"
            exit 1
        else
            find-fd-upward $(readlink -ef $1/..)
        fi
    fi
}

find-fd-upward $(dirname $(readlink -ef $0))

log_options=$(if $VERBOSE ; then echo "--log-level info" ; else echo "--log-level warning" ; fi)

plan(){
    echo $(whoami)@$(hostname)
    time echodo $fdscript --search --validate \
         --plan-file $probdir/$probname.plan $log_options problem.pddl \
         --search 'astar(merge_and_shrink(shrink_strategy=shrink_bisimulation(max_states=50000,greedy=false),merge_strategy=merge_dfp(),label_reduction=exact(before_shrinking=true,before_merging=false)))'
    #  # --alias lama-first
}

finalize (){
    :
}

negatively-proven (){
    grep "Completely explored state space" log &> /dev/null
}

report-results (){
    awk "/Plan cost:/{print $2}" log | sort | head -n 1
}

plan-found (){
    ls $probdir/$probname.plan*
}

################################################################

. $SCRDIR/common.sh
