#!/bin/bash
#-*- mode:sh -*-

################################################################
#### default options

bin=$SCRDIR/mff-myself

################################################################
#### main

plan(){
    vecho $(whoami)@$(hostname)
    vechodo $bin $(if $VERBOSE ; then echo "-i 3" ; fi) $OPTIONS \
        -f problem.pddl -o domain.pddl
}

finalize (){
    grep "^\(step\)\?\s*[0-9]\+: \(.*\)" log | cut -d: -f 2 | sed -e "s/^ \(.*\)/(\1)/g" > plan
    [[ $(cat plan | wc -l) -gt 0 ]] && vcp plan $probdir/$probname.plan
}

negatively-proven (){
    grep "problem proven unsolvable" log || \
        grep "No plan will solve it" log
}

report-results (){
    local cost=$(cat plan | wc -l)
    [[ -e plan && $cost -gt 0 ]] && echo "Plan cost: " $cost
    [[ -e plan && $cost -gt 0 ]]
}

################################################################

. $SCRDIR/common.sh
