#!/bin/bash
#-*- mode:sh -*-

################################################################
#### default options

bin=$SCRDIR/MpC

################################################################
#### main

plan(){
    vecho $(whoami)@$(hostname)
    vechodo $bin domain.pddl problem.pddl -Q $OPTIONS
}

finalize (){
    awk '/^[0-9]+ +:.*/{ y=match($0,/\(.*\)/); print substr($0,RSTART,RLENGTH)}' $log > plan
    [[ $(cat plan | wc -l) -gt 0 ]] && vcp plan $probdir/$probname.plan
}

negatively-proven (){
    grep "problem proven unsolvable" $log || \
        grep "No plan will solve it" $log
}

report-results (){
    local cost=$(cat plan | wc -l)
    [[ -e plan && $cost -gt 0 ]] && echo "Plan cost: " $cost
}

plan-found (){
    local cost=$(cat plan | wc -l)
    [[ -e plan && $cost -gt 0 ]]
}

################################################################

. $SCRDIR/common.sh
