#!/bin/bash
#-*- mode:sh -*-

################################################################
#### default options



################################################################
#### main

plan(){
    vecho $(whoami)@$(hostname)
    cp $probdir/p01.pddl ./
    cp $probdir/p02.pddl ./
    cp $probdir/p03.pddl ./
    vechodo $SCRDIR/sol-ep-base.sh domain.pddl problem.pddl p01.pddl p02.pddl p03.pddl
}

finalize (){
    pwd
    if [[ -e pro.soln ]]
    then
        cat pro.soln | grep -v "^Time" > plan
        [[ $(cat plan | wc -l) -gt 0 ]] && vcp plan $probdir/$probname.plan
    else
        vecho "No plan found!"
    fi
}

negatively-proven (){
    grep "problem proven unsolvable" log
}

report-results (){
    local cost=$(cat plan | wc -l)
    [[ -e plan && $cost -gt 0 ]] && echo "Plan cost: " $cost
    [[ -e plan && $cost -gt 0 ]]
}

################################################################

. $SCRDIR/common.sh
