#!/bin/bash
#-*- mode:sh -*-

################################################################
#### default options

bin="$SCRDIR/cpt_yahsp3_64 -y 1"

################################################################
#### main

plan(){
    vecho $(whoami)@$(hostname)
    vechodo $bin $(if $VERBOSE ; then echo "-v 3" ; fi) $OPTIONS \
        -f problem.pddl -o domain.pddl
}

finalize (){
    grep "^\(step\)\?\s*[0-9]\+: \(.*\)" log | cut -d: -f 2 | sed -e "s/^ \(.*\)/(\1)/g" > plan
    [[ $(cat plan | wc -l) -gt 0 ]] && \
        sbcl --script $SCRDIR/yahsp3-parse-result.lisp < plan > $probdir/$probname.plan
}

negatively-proven (){
    grep "problem proven unsolvable" log || \
        grep "No plan will solve it" log
}

report-results (){
    local cost=$(grep Length log | cut -d" " -f3)
    [[ -e plan && $cost -gt 0 ]] && echo "Plan cost: " $cost
}

plan-found (){
    local cost=$(grep Length log | cut -d" " -f3)
    [[ -e plan && $cost -gt 0 ]]
}

################################################################

. $SCRDIR/common.sh
